-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-20 23:18:57 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE location (
    country   VARCHAR2(28) NOT NULL,
    city      VARCHAR2(28) NOT NULL
);

ALTER TABLE location ADD CONSTRAINT location_pk PRIMARY KEY ( city,
                                                              country );

CREATE TABLE match (
    match_id     INTEGER NOT NULL,
    dates        DATE,
    tournament   VARCHAR2(38),
    neutral      VARCHAR2(28)
);

ALTER TABLE match ADD CONSTRAINT match_pk PRIMARY KEY ( match_id );

CREATE TABLE play (
    match_match_id    INTEGER
     NOT NULL,
    team_team          VARCHAR2(28) NOT NULL,
    location_city      VARCHAR2(28) NOT NULL,
    location_country   VARCHAR2(28) NOT NULL
);

CREATE UNIQUE INDEX play__idx ON
    play (
        match_match_id
    ASC );

CREATE TABLE player (
    personid   INTEGER NOT NULL,
    name       VARCHAR2(38) NOT NULL,
    position   VARCHAR2(6),
    rating     INTEGER
);

ALTER TABLE player ADD CONSTRAINT player_pk PRIMARY KEY ( personid,
                                                          name );

CREATE TABLE team (
    team VARCHAR2(28) NOT NULL
);

ALTER TABLE team ADD CONSTRAINT team_pk PRIMARY KEY ( team );

CREATE TABLE team_player (
    team_team         VARCHAR2(28) NOT NULL,
    player_personid   INTEGER NOT NULL,
    player_name       VARCHAR2(38) NOT NULL
);

CREATE UNIQUE INDEX team_player__idx ON
    team_player (
        player_personid
    ASC,
        player_name
    ASC );

CREATE UNIQUE INDEX team_player__idxv1 ON
    team_player (
        team_team
    ASC );

ALTER TABLE play
    ADD CONSTRAINT play_location_fk FOREIGN KEY ( location_city,
                                                  location_country )
        REFERENCES location ( city,
                              country );

ALTER TABLE play
    ADD CONSTRAINT play_match_fk FOREIGN KEY ( match_match_id )
        REFERENCES match ( match_id );

ALTER TABLE play
    ADD CONSTRAINT play_team_fk FOREIGN KEY ( team_team )
        REFERENCES team ( team );

ALTER TABLE team_player
    ADD CONSTRAINT team_player_player_fk FOREIGN KEY ( player_personid,
                                                       player_name )
        REFERENCES player ( personid,
                            name );

ALTER TABLE team_player
    ADD CONSTRAINT team_player_team_fk FOREIGN KEY ( team_team )
        REFERENCES team ( team );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             3
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   2
-- WARNINGS                                 0
